# ==========================================
# 1. DATABASE ENGINE CORE CONNECTION CONFIG
# ==========================================
spring.datasource.url=jdbc:mysql://localhost:3306/dp_products?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=GAviKPri@57

# ==========================================
# 2. HIBERNATE ORM TRANSLATION ENGINE RULES
# ==========================================
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# 'update' matches your code variables to the columns safely without wiping data
spring.jpa.hibernate.ddl-auto=update
# Prints clean SQL statements in your terminal window for fast debugging
spring.jpa.show-sql=true

# ==========================================
# GMAIL SMTP RELAY INTEGRATION PROPERTIES
# ==========================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=priyankakommana05@gmail.com
# Use an explicit App Password generated from your Google Account settings, NOT your regular password
spring.mail.password=egleksdpcecovolk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

